name: ride2gather
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  mysql_client: ^0.0.27
  crypto: ^3.0.3
  http: ^1.2.2

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^6.2.1
  lottie: ^1.4.2

  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.3.0
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3

  path_provider: ^2.0.11
  uuid: ^3.0.6
  mime: ^1.0.2
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
